# Generated by Django 4.1.4 on 2025-07-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airline_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline',
            new_name='Airport',
        ),
    ]
